version: '3.6'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    hostname: frontend
    restart: always
    ports:
      - "3000:80"  # Map external port 80 to internal port 3000
    networks:
      - mymernapp

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend
    hostname: backend
    ports:
      - "8080:8080"
    restart: always
    networks:
      - mymernapp
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mymernappdb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: my_mern_app_db
    networks:
      - mymernapp
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mymernappdb:
    name: mymernappdb

networks:
  mymernapp:
    driver: bridge
