version: '3.6'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    hostname: frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app       # Bind mount for live reload
      - /app/node_modules
    networks:
      - mymernapp

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    hostname: backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    restart: always
    volumes:
      - ./backend:/app        # Bind mount for live reload
      - /app/node_modules
    networks:
      - mymernapp
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mymernappdb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: my_mern_app_db
    networks:
      - mymernapp
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mymernappdb:
    name: mymernappdb

networks:
  mymernapp:
    driver: bridge
